//
// Copyright(C) 1993-1996 Id Software, Inc.
// Copyright(C) 2005-2014 Simon Howard
//
// DESCRIPTION:
//  Created by a sound utility. Kept as a sample, DOOM2 sounds.
//
// Original: sounds.h / sounds.c

use std::sync::{Mutex, OnceLock};

use super::i_sound::{MusicInfo, SfxInfo};

static S_SFX: OnceLock<Mutex<Vec<SfxInfo>>> = OnceLock::new();
static S_MUSIC: OnceLock<Vec<MusicInfo>> = OnceLock::new();

fn sfx_name(s: &str) -> [u8; 9] {
    let mut a = [0u8; 9];
    let bytes = s.as_bytes();
    let len = bytes.len().min(8);
    a[..len].copy_from_slice(&bytes[..len]);
    a
}

fn sound(name: &str, priority: i32) -> SfxInfo {
    SfxInfo {
        tagname: None,
        name: sfx_name(name),
        priority,
        link: None,
        pitch: -1,
        volume: -1,
        usefulness: 0,
        lumpnum: -1,
        numchannels: 1,
    }
}

fn sound_link(name: &str, priority: i32, link_id: usize, pitch: i32, volume: i32) -> SfxInfo {
    SfxInfo {
        tagname: None,
        name: sfx_name(name),
        priority,
        link: Some(link_id),
        pitch,
        volume,
        usefulness: 0,
        lumpnum: -1,
        numchannels: 1,
    }
}

fn music(name: Option<&str>) -> MusicInfo {
    MusicInfo {
        name: name.map(|s| s.to_string()),
        lumpnum: 0,
        data: None,
    }
}

/// Identifiers for all music in game.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum MusicEnum {
    None = 0,
    E1m1,
    E1m2,
    E1m3,
    E1m4,
    E1m5,
    E1m6,
    E1m7,
    E1m8,
    E1m9,
    E2m1,
    E2m2,
    E2m3,
    E2m4,
    E2m5,
    E2m6,
    E2m7,
    E2m8,
    E2m9,
    E3m1,
    E3m2,
    E3m3,
    E3m4,
    E3m5,
    E3m6,
    E3m7,
    E3m8,
    E3m9,
    Inter,
    Intro,
    Bunny,
    Victor,
    Introa,
    Runnin,
    Stalks,
    Countd,
    Betwee,
    Doom,
    TheDa,
    Shawn,
    Ddtblu,
    InCit,
    Dead,
    Stlks2,
    Theda2,
    Doom2,
    Ddtbl2,
    Runni2,
    Dead2,
    Stlks3,
    Romero,
    Shawn2,
    Messag,
    Count2,
    Ddtbl3,
    Ampie,
    Theda3,
    Adrian,
    Messg2,
    Romer2,
    Tense,
    Shawn3,
    Openin,
    Evil,
    Ultima,
    ReadM,
    Dm2ttl,
    Dm2int,
}

pub const NUMMUSIC: usize = MusicEnum::Dm2int as usize + 1;

/// Identifiers for all sfx in game.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum SfxEnum {
    None = 0,
    Pistol,
    Shotgn,
    Sgcock,
    Dshtgn,
    Dbopn,
    Dbcls,
    Dbload,
    Plasma,
    Bfg,
    Sawup,
    Sawidl,
    Sawful,
    Sawhit,
    Rlaunc,
    Rxplod,
    Firsht,
    Firxpl,
    Pstart,
    Pstop,
    Doropn,
    Dorcls,
    Stnmov,
    Swtchn,
    Swtchx,
    Plpain,
    Dmpain,
    Popain,
    Vipain,
    Mnpain,
    Pepain,
    Slop,
    Itemup,
    Wpnup,
    Oof,
    Telept,
    Posit1,
    Posit2,
    Posit3,
    Bgsit1,
    Bgsit2,
    Sgtsit,
    Cacsit,
    Brssit,
    Cybsit,
    Spisit,
    Bspsit,
    Kntsit,
    Vilsit,
    Mansit,
    Pesit,
    Sklatk,
    Sgtatk,
    Skepch,
    Vilatk,
    Claw,
    Skeswg,
    Pldeth,
    Pdiehi,
    Podth1,
    Podth2,
    Podth3,
    Bgdth1,
    Bgdth2,
    Sgtdth,
    Cacdth,
    Skldth,
    Brsdth,
    Cybdth,
    Spidth,
    Bspdth,
    Vildth,
    Kntdth,
    Pedth,
    Skedth,
    Posact,
    Bgact,
    Dmact,
    Bspact,
    Bspwlk,
    Vilact,
    Noway,
    Barexp,
    Punch,
    Hoof,
    Metal,
    Chgun,
    Tink,
    Bdopn,
    Bdcls,
    Itmbk,
    Flame,
    Flamst,
    Getpow,
    Bospit,
    Boscub,
    Bossit,
    Bospn,
    Bosdth,
    Manatk,
    Mandth,
    Sssit,
    Ssdth,
    Keenpn,
    Keendt,
    Skeact,
    Skesit,
    Skeatk,
    Radio,
}

pub const NUMSFX: usize = SfxEnum::Radio as usize + 1;

fn build_s_music() -> Vec<MusicInfo> {
    vec![
        music(None),
        music(Some("e1m1")),
        music(Some("e1m2")),
        music(Some("e1m3")),
        music(Some("e1m4")),
        music(Some("e1m5")),
        music(Some("e1m6")),
        music(Some("e1m7")),
        music(Some("e1m8")),
        music(Some("e1m9")),
        music(Some("e2m1")),
        music(Some("e2m2")),
        music(Some("e2m3")),
        music(Some("e2m4")),
        music(Some("e2m5")),
        music(Some("e2m6")),
        music(Some("e2m7")),
        music(Some("e2m8")),
        music(Some("e2m9")),
        music(Some("e3m1")),
        music(Some("e3m2")),
        music(Some("e3m3")),
        music(Some("e3m4")),
        music(Some("e3m5")),
        music(Some("e3m6")),
        music(Some("e3m7")),
        music(Some("e3m8")),
        music(Some("e3m9")),
        music(Some("inter")),
        music(Some("intro")),
        music(Some("bunny")),
        music(Some("victor")),
        music(Some("introa")),
        music(Some("runnin")),
        music(Some("stalks")),
        music(Some("countd")),
        music(Some("betwee")),
        music(Some("doom")),
        music(Some("the_da")),
        music(Some("shawn")),
        music(Some("ddtblu")),
        music(Some("in_cit")),
        music(Some("dead")),
        music(Some("stlks2")),
        music(Some("theda2")),
        music(Some("doom2")),
        music(Some("ddtbl2")),
        music(Some("runni2")),
        music(Some("dead2")),
        music(Some("stlks3")),
        music(Some("romero")),
        music(Some("shawn2")),
        music(Some("messag")),
        music(Some("count2")),
        music(Some("ddtbl3")),
        music(Some("ampie")),
        music(Some("theda3")),
        music(Some("adrian")),
        music(Some("messg2")),
        music(Some("romer2")),
        music(Some("tense")),
        music(Some("shawn3")),
        music(Some("openin")),
        music(Some("evil")),
        music(Some("ultima")),
        music(Some("read_m")),
        music(Some("dm2ttl")),
        music(Some("dm2int")),
    ]
}

fn build_s_sfx() -> Vec<SfxInfo> {
    let pistol_idx = SfxEnum::Pistol as usize;
    let mut sfx = vec![
        sound("none", 0),
        sound("pistol", 64),
        sound("shotgn", 64),
        sound("sgcock", 64),
        sound("dshtgn", 64),
        sound("dbopn", 64),
        sound("dbcls", 64),
        sound("dbload", 64),
        sound("plasma", 64),
        sound("bfg", 64),
        sound("sawup", 64),
        sound("sawidl", 118),
        sound("sawful", 64),
        sound("sawhit", 64),
        sound("rlaunc", 64),
        sound("rxplod", 70),
        sound("firsht", 70),
        sound("firxpl", 70),
        sound("pstart", 100),
        sound("pstop", 100),
        sound("doropn", 100),
        sound("dorcls", 100),
        sound("stnmov", 119),
        sound("swtchn", 78),
        sound("swtchx", 78),
        sound("plpain", 96),
        sound("dmpain", 96),
        sound("popain", 96),
        sound("vipain", 96),
        sound("mnpain", 96),
        sound("pepain", 96),
        sound("slop", 78),
        sound("itemup", 78),
        sound("wpnup", 78),
        sound("oof", 96),
        sound("telept", 32),
        sound("posit1", 98),
        sound("posit2", 98),
        sound("posit3", 98),
        sound("bgsit1", 98),
        sound("bgsit2", 98),
        sound("sgtsit", 98),
        sound("cacsit", 98),
        sound("brssit", 94),
        sound("cybsit", 92),
        sound("spisit", 90),
        sound("bspsit", 90),
        sound("kntsit", 90),
        sound("vilsit", 90),
        sound("mansit", 90),
        sound("pesit", 90),
        sound("sklatk", 70),
        sound("sgtatk", 70),
        sound("skepch", 70),
        sound("vilatk", 70),
        sound("claw", 70),
        sound("skeswg", 70),
        sound("pldeth", 32),
        sound("pdiehi", 32),
        sound("podth1", 70),
        sound("podth2", 70),
        sound("podth3", 70),
        sound("bgdth1", 70),
        sound("bgdth2", 70),
        sound("sgtdth", 70),
        sound("cacdth", 70),
        sound("skldth", 70),
        sound("brsdth", 32),
        sound("cybdth", 32),
        sound("spidth", 32),
        sound("bspdth", 32),
        sound("vildth", 32),
        sound("kntdth", 32),
        sound("pedth", 32),
        sound("skedth", 32),
        sound("posact", 120),
        sound("bgact", 120),
        sound("dmact", 120),
        sound("bspact", 100),
        sound("bspwlk", 100),
        sound("vilact", 100),
        sound("noway", 78),
        sound("barexp", 60),
        sound("punch", 64),
        sound("hoof", 70),
        sound("metal", 70),
        sound_link("chgun", 64, pistol_idx, 150, 0),
        sound("tink", 60),
        sound("bdopn", 100),
        sound("bdcls", 100),
        sound("itmbk", 100),
        sound("flame", 32),
        sound("flamst", 32),
        sound("getpow", 60),
        sound("bospit", 70),
        sound("boscub", 70),
        sound("bossit", 70),
        sound("bospn", 70),
        sound("bosdth", 70),
        sound("manatk", 70),
        sound("mandth", 70),
        sound("sssit", 70),
        sound("ssdth", 70),
        sound("keenpn", 70),
        sound("keendt", 70),
        sound("skeact", 70),
        sound("skesit", 70),
        sound("skeatk", 70),
        sound("radio", 60),
    ];
    sfx
}

/// The complete set of music (immutable).
pub fn s_music() -> &'static [MusicInfo] {
    S_MUSIC.get_or_init(build_s_music).as_slice()
}

/// The complete set of sound effects (mutable for lumpnum, usefulness).
pub fn s_sfx() -> &'static Mutex<Vec<SfxInfo>> {
    S_SFX.get_or_init(|| Mutex::new(build_s_sfx()))
}
