//! Rust translation of doomgeneric/config.h
//! Autogenerated config from configure.

/// C #define: HAVE_INTTYPES_H
pub const HAVE_INTTYPES_H: i32 = 1;
/// C #define: HAVE_STDINT_H
pub const HAVE_STDINT_H: i32 = 1;
/// C #define: HAVE_STDLIB_H
pub const HAVE_STDLIB_H: i32 = 1;
/// C #define: HAVE_STRINGS_H
pub const HAVE_STRINGS_H: i32 = 1;
/// C #define: HAVE_STRING_H
pub const HAVE_STRING_H: i32 = 1;
/// C #define: HAVE_SYS_TYPES_H
pub const HAVE_SYS_TYPES_H: i32 = 1;
/// C #define: STDC_HEADERS
pub const STDC_HEADERS: i32 = 1;

/// C #define: PACKAGE
pub static PACKAGE: &str = "Doom";
/// C #define: PACKAGE_NAME
pub static PACKAGE_NAME: &str = "Doom Generic";
/// C #define: PACKAGE_STRING
pub static PACKAGE_STRING: &str = "Doom Generic 0.1";
/// C #define: PACKAGE_TARNAME
pub static PACKAGE_TARNAME: &str = "doomgeneric.tar";
/// C #define: PACKAGE_VERSION
pub const PACKAGE_VERSION: f64 = 0.1;
/// C #define: PROGRAM_PREFIX
pub static PROGRAM_PREFIX: &str = "doomgeneric";
/// C #define: VERSION
pub static VERSION: &str = "0.1";
/// C #define: FILES_DIR
pub static FILES_DIR: &str = ".";
