//! Dehacked misc defaults (deh_misc.h)
//! Original: deh_misc.h
//! Plan §4: FEATURE_DEHACKED unused - use hard-coded default path.

// #define DEH_DEFAULT_INITIAL_HEALTH 100
pub const DEH_DEFAULT_INITIAL_HEALTH: i32 = 100;
// #define DEH_DEFAULT_INITIAL_BULLETS 50
pub const DEH_DEFAULT_INITIAL_BULLETS: i32 = 50;
// #define DEH_DEFAULT_MAX_HEALTH 200
pub const DEH_DEFAULT_MAX_HEALTH: i32 = 200;
// #define DEH_DEFAULT_MAX_ARMOR 200
pub const DEH_DEFAULT_MAX_ARMOR: i32 = 200;
// #define DEH_DEFAULT_GREEN_ARMOR_CLASS 1
pub const DEH_DEFAULT_GREEN_ARMOR_CLASS: i32 = 1;
// #define DEH_DEFAULT_BLUE_ARMOR_CLASS 2
pub const DEH_DEFAULT_BLUE_ARMOR_CLASS: i32 = 2;
// #define DEH_DEFAULT_MAX_SOULSPHERE 200
pub const DEH_DEFAULT_MAX_SOULSPHERE: i32 = 200;
// #define DEH_DEFAULT_SOULSPHERE_HEALTH 100
pub const DEH_DEFAULT_SOULSPHERE_HEALTH: i32 = 100;
// #define DEH_DEFAULT_MEGASPHERE_HEALTH 200
pub const DEH_DEFAULT_MEGASPHERE_HEALTH: i32 = 200;
// #define DEH_DEFAULT_GOD_MODE_HEALTH 100
pub const DEH_DEFAULT_GOD_MODE_HEALTH: i32 = 100;
// #define DEH_DEFAULT_IDFA_ARMOR 200
pub const DEH_DEFAULT_IDFA_ARMOR: i32 = 200;
// #define DEH_DEFAULT_IDFA_ARMOR_CLASS 2
pub const DEH_DEFAULT_IDFA_ARMOR_CLASS: i32 = 2;
// #define DEH_DEFAULT_IDKFA_ARMOR 200
pub const DEH_DEFAULT_IDKFA_ARMOR: i32 = 200;
// #define DEH_DEFAULT_IDKFA_ARMOR_CLASS 2
pub const DEH_DEFAULT_IDKFA_ARMOR_CLASS: i32 = 2;
// #define DEH_DEFAULT_BFG_CELLS_PER_SHOT 40
pub const DEH_DEFAULT_BFG_CELLS_PER_SHOT: i32 = 40;
// #define DEH_DEFAULT_SPECIES_INFIGHTING 0
pub const DEH_DEFAULT_SPECIES_INFIGHTING: i32 = 0;
